- name: Create Users
  hosts: coreos
  tasks:
    - name: deploy public key JFA
      authorized_key:
        key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIRAzjzasfdfp6sRL9fJgTufLy0TbnQs/YR6di0iIpd3lhebLgoT8JFdVoijNlK7vENGoAUW1IeUPJilpEaCVF0= jfader@fader-t510'
        user: core
    - name: deploy public key hug
      authorized_key:
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCn4XCDsbu85OccehXtYURPpha5/IQqsjuveElCxkzIe0zNmN6KlXZf89pzARiHS251lKWXnvyQPZd9ABhcGy4VrsmXOnDVPNvx+iYyCFCNl8joZyqg7MU5B7ByofektxJmE8uZusP7WyHnUnyeF8nHg/qCdNWAZb/WjGLq5JyhgKfvHsRQFbtZfagj8VGxP4pO8OD4kvMbCLfNUncae5SHeL1smNuHNCrpRgRNir7QRuRpLjk40IMNA+hw/s1a75CgfKVhv57pYsaBE/JiWeI0RocOxV/EI9cogpyrMKeLEQg9I8FvbbJu4V98NJByD9Ecu4O2nRnRfOW1edeMr+A5 hugtest@unknown'
        user: core
